api_version = "2025-10"

[[extensions]]
uid = "wishlist-fullpage-extension"
type = "ui_extension"
name = "My Wishlist"
handle = "wishlist-fullpage"

[[extensions.targeting]]
module = "./src/WishlistPage.jsx"
target = "customer-account.page.render"

[[extensions.targeting]]
module = "./src/ProfileBlock.jsx"
target = "customer-account.profile.block.render"

[extensions.capabilities]
api_access = true
network_access = true
